import Navigation from "./navigation";
import Head from "next/head";

const Layout = ({title, children}) => {
  return (
    <div>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app"/>
        <link rel="icon" href="/favicon.ico"/>
        <link rel='stylesheet' href='https://cdn.jsdelivr.net/npm/bootswatch@4.5.2/dist/flatly/bootstrap.min.css'/>



      </Head>

      <Navigation/>
      <div className='container'>
        {children}
      </div>
    </div>
  )
}

export default Layout
